apiVersion: v1
kind: Secret
metadata:
  name: interview-app-secret
  namespace: default
type: Opaque
data:
  API_KEY: c2VjcmV0
  DYNATRACE_API_URL: aHR0cHM6Ly93d242MjUxMi5saXZlLmR5bmF0cmFjZS5jb20=
  DYNATRACE_API_TOKEN: ZHQwYzAxLlhXQUtLN0lHSE1ZVUxKQVA1WUk1NldLMi5XSFdPM05EUVRBRDJaNE1JQ1FDN1k3NTIzWEtZUVY2MlRDTVhON1JFVzRMSlREVTY0VUFNQlNMNzYyM0RDVTVB
